### ISSUE TITLE
compose up fails

### ISSUE THREAD

**Issue by machzqcq** [DanWahlin/AspNetCorePostgreSQLDockerApp#1]
docker-compose build passes
docker-compose up fails as below

![danwahlin](https://cloud.githubusercontent.com/assets/6425159/14933014/75ab00a8-0e4f-11e6-9ccf-39cba35f667b.png)

```
pradeep@seleniumframework>docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 23
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 109
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.19-boot2docker
Operating System: Boot2Docker 1.11.0 (TCL 7.0); HEAD : 32ee7e9 - Wed Apr 13 20:06:49 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: FPNF:IOLP:R67R:5JQ2:EMQX:ZUKM:DBNV:3NUZ:UUKN:G2QL:5325:4ZUO
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 13
 Goroutines: 30
 System Time: 2016-04-30T01:15:24.064491054Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Comment by DanWahlin** [comment]
Thanks Pradeep...I'm seeing the same thing now unfortunately (sad part is it was working fine very recently). Not something I have time to look into right now unfortunately due to my travel schedule, but if you happen to find anything please let me know. When I get time to look into it more I'll let you know if I find anything.

**Comment by DanWahlin** [comment]
I took a quick look into this and it appears that different packages are being pulled down compared to when it was working correctly - at least that's what I'm thinking at this point. It's because * was used in the versions within project.json from what I can tell. It's not something I will be able to fix right away and since ASP.NET Core is going through significant changes right now I'm going to hold off on updates until it stabilizes more.

**Comment by DanWahlin** [comment]
This is fixed now (thanks to a ton of help from my buddy @spboyer!). Major update from the previous version that was initially released.
