### ISSUE TITLE
aspnetcore.development.dockerfile fail

### ISSUE THREAD

**Issue by Yip-Yip** [DanWahlin/AspNetCorePostgreSQLDockerApp#8]
FYI Environment Windows 10 machine
aspnetcore proj fails on build cant find csproj 

Fix 

(1)
aspnetcore.development.dockerfile
/*
FROM microsoft/dotnet:2.1-sdk

LABEL author="Dan Wahlin"

ENV DOTNET_USE_POLLING_FILE_WATCHER=1
ENV ASPNETCORE_URLS=http://*:5000

EXPOSE 5000

WORKDIR /var/www/aspnetcoreapp

COPY AspNetCorePostgreSQLDockerApp.csproj .

CMD ["/bin/bash", "-c", "dotnet restore AspNetCorePostgreSQLDockerApp.csproj && dotnet run"]
*/

(2)
docker build -f aspnetcore.development.dockerfile -t [insert docker id]/dotnet:1.0.0 .

(3)
docker run -d  -p 5000:5000 -v "%cd%":/var/www/aspnetcoreapp  --link my-postgres:postgres [insert docker id]/dotnet:1.0.0

**Comment by DanWahlin** [comment]
For the development dockerfile you'd need to setup a volume that points to the source code. That's why you're getting an error. COPY would only be used for the production version where you want to copy the actual code into the image. 

In the readme you'll see instructions for running things using Docker Compose and you'll find a volume setup in the docker-compose.yml file. Hope that helps.

**Comment by Yip-Yip** [comment]
I understand that there is a mixture of old/new sample files as noted in your course. 

Just finishing "Managing Containers with Docker Compose" 

We are a small startup, would it be correct in assuming that docker-compose should do us well and that Kubernettes is overkill until we need to scale in a Large way. 

And finally I was reading that docker cloud is EOL ? 

Thanks

Justin
